# 1. For build React app
FROM node:14 AS development

# Set working directory
WORKDIR /app

# 
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

# Same as npm install
RUN npm install

COPY . /app

CMD [ "npm", "start" ]

FROM development AS build

RUN npm run build
CMD npm start